CREATE DATABASE QLKS CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

use QLKS;
DROP TABLE NHANVIEN;

CREATE TABLE NHANVIEN(
	MaNV CHAR(10) PRIMARY KEY,
	HoTenNV VARCHAR(100),
	GioiTinh VARCHAR(10),
	NgaySinh DATE,
	ChucVu VARCHAR(50)
);

CREATE TABLE PHONG(
	MaPhong CHAR(10) PRIMARY KEY,
	TenPhong VARCHAR(50),
	LoaiPhong VARCHAR(50),
	Gia DECIMAL(18,2),
	TrangThai VARCHAR(20)
);

CREATE TABLE KHACHHANG(
	MaKH CHAR(10) PRIMARY KEY,
	HoTenKH VARCHAR(100),
	QuocTich VARCHAR(50),
	Sdt CHAR(10),
	Email VARCHAR(50)
);

CREATE TABLE DICHVU (
	MaDV CHAR(10) PRIMARY KEY,
	TenDV VARCHAR(100),
	GiaDV DECIMAL(18,2)
);

CREATE TABLE DATPHONG(
	MaDatPhong CHAR(10) PRIMARY KEY,
	MaKH CHAR(10),
	MaPhong CHAR(10),
	NgayDat DATE,
	NgayTra DATE,
	SoLuongKhach INT,
	GhiChu NVARCHAR(200)
);

CREATE TABLE HOADON(
	MaHoaDon CHAR(10) PRIMARY KEY,
	MaNVThanhToan CHAR(10),
	MaKH CHAR(10),
	MaPhong CHAR(10),
	MaDV CHAR(10),
	SoLuongPhong INT,
	SoLuongDV INT,
	TongTien DECIMAL(18,2)
);
